### PR TITLE
fix: add volume_name for postgres in config.yaml

### PR DESCRIPTION
**Pull request by MPK1**
## Problem

Under several circumstances, the postgres container might not be able to write in the mounted data directory due to wrong permissions (should be 700) or wrong ownership (should be uid 999).

This PR solves several issues like:
- https://github.com/nhost/cli/issues/237
- https://github.com/nhost/cli/issues/235

## Solution

The `volume_name` option is added to the `config.yaml`. If it is set, the postgres data will be stored in a docker volume instead of in a directory with bind mount. The given string will be used as name for the volume.

Example:
```
services:
  postgres:
    version: 14
    volume_name: nhost_postgresql_data
    environment:
      postgres_password: postgres
      postgres_user: postgres
```

### CODE REVIEW

**Comment by MPK1** [comment]
Hello dear contributors/maintainers (with write access),

if you have a minute to look at my code, I would be very happy to receive some feedback, either a review or a comment. It's only 7 new LOC :)

I consider the added functionality not only as a fix but also as an added feature, as docker encourages users to use named volumes instead of bind mounts (they seem to be more stable on different OS and easier for users new to docker).

Thank you and have a nice day!

**Comment by elephant3** [comment]
Hello @MPK1 and thank you very much for your contribution. We're preparing a big release of the new CLI. This PR will unlikely be merged, but I'll take a look and make the new release takes into account your proposal.

**Comment by nunopato** [comment]
@elephant3 I think this PR can be closed, correct?

**Comment by elephant3** [comment]
@MPK1 could you confirm that this issue still persists for you in the latest CLI?

**Comment by MPK1** [comment]
> @MPK1 could you confirm that this issue still persists for you in the latest CLI?

Looks good, the issue seems to be fixed. It had some ownership issues with the pgdata directory, which should be an issue for new projects. This issue as well as #235 should be fixed.

**Pull request closed without merging**
