### PR TITLE
fix: pass hasura's env vars to the hasura console

### PR DESCRIPTION
**Pull request by atbe**
## Description

chore: Pass all environment variables to "console" service for local testing

## Problem

Events using environment variables can't be locally tested due to these variables not being available in the "console" service defined in the docker-compose file.

## Solution

This PR modifies the docker-compose file generator to include all environment variables, making them accessible to the "console" service. This allows for easier local testing of events dependent on these variables.

## Notes

Exercise caution with sensitive information; make sure to filter out sensitive environment variables before they are passed to the "console" service.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Thanks for the fix, the changes look good but the tests are broken, would you mind fixing? Thanks!

**Comment by atbe** [comment]
@dbarrosop I would be happy to, but the output of the tests are unclear and don't give me any indication of what's failing, and the tests are failing to run on a Mac where they throw an error:

```bash
error: flake 'git+file:///Users/ibrahimahmed/code/nhost-projecrs/nhost-cli' does not provide attribute 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
```

If you could kindly fix the error, I would really appreciate it, otherwise I'll fire up a linux machine to try to get it fixed.

**Comment by dbarrosop** [comment]
You should be able to just run `go test ./...` if needed

**Comment by dbarrosop** [comment]
Merged via 2aff9fd8cf5dcda4a7cc4276362518bc3840df22

**Pull request closed without merging**
